export const portfolio = [
	{
		id: 1,
		name: "EcommerceSHOP",
		img: "shop_project.png",
		tech: ["react.svg", "tailwind.svg", "node.svg", "express.svg", "mongodb.svg"],
		url: "https://imperio-shoes.vercel.app/",
		repository: "https://github.com/gszcode/Ecommerce-MERN",
	},
	{
		id: 2,
		name: "Imperio Shoes",
		img: "ecommerce_project.PNG",
		tech: ["typescript.svg", "next.svg", "sass.svg", "node.svg", "express.svg", "postgresql.svg"],
		url: "https://imperio-shoes.vercel.app/",
		repository: "https://github.com/gszcode/E-commerce-Client",
	},
	{
		id: 3,
		name: "Sharpness",
		img: "sharpness_project.png",
		tech: ["typescript.svg", "react.svg", "css.svg"],
		url: "https://sharpness.vercel.app/",
		repository: "https://github.com/gszcode/sharpness",
	},
	{
		id: 4,
		name: "Consultant",
		img: "consultant_project.png",
		tech: ["react.svg", "css.svg", "node.svg", "mongodb.svg"],
		url: "https://gscode.vercel.app/",
		repository: "https://github.com/gszcode/gscode",
	},
	{
		id: 5,
		name: "PsyCare",
		img: "psycare_project.png",
		tech: ["javascript.svg", "react.svg", "css.svg"],
		url: "https://psycares.netlify.app/",
		repository: "https://github.com/gszcode/psycare",
	},
	{
		id: 6,
		name: "Portfolio",
		img: "portfolio_project.png",
		tech: ["javascript.svg", "react.svg", "css.svg"],
		url: "https://gabriel-sanchez.vercel.app/",
		repository: "https://github.com/gszcode/new-portfolio",
	},
];
